### ISSUE TITLE
simfloats

### ISSUE THREAD

**Issue by timchurches** [Chysn/O_C-Hemisphere#1]
https://github.com/Chysn/O_C-Hemisphere/blob/2c8e9b42c698221ab76c91b26b167d65a8e71e6b/software/o_c_REV/HemisphereApplet.h#L17

Might be faster if you use right and left bit-shifts in your simfloat macro eg instead of:

#define int2simfloat(x) 10000 * (x)
#define simfloat2int(x) (x) / 10000

something like:

#define int2simfloat(x) (x << 14)
#define simfloat2int(x) (x >> 14)

although it is probably necessary to use int32_t for the type to avoid overflow.

**Comment by Chysn** [comment]
Oh, yeah, good catch. Thanks!

**Comment by Chysn** [comment]
Implemented 6/25. Thank you once again!
