### ISSUE TITLE
The module is freezing in Quadraturia app in the last few Hemisphere updates

### ISSUE THREAD

**Issue by Shayshez** [Chysn/O_C-Hemisphere#2]
I'm updating the Hemisphere firmware once in few days (when updates is released).
in the last few updates there is problem with the LFO inside Hemisphere (there is horizontal lines on the screen, only on the side of the LFO) and when I'm trying to open Quadraturia app the module is freezing.
https://youtu.be/Wyv-tgZanPM

**Comment by Chysn** [comment]
Shayshez, thank you for your help in tracking down this issue!
