### ISSUE TITLE
Hemisphere current version

### ISSUE THREAD

**Issue by pablobcb** [Chysn/O_C-Hemisphere#3]
Hello,

I have recently purchased a micro O_c, and asked for the builder to ship it with the hemisphere firmware. But it looks like I have some functionally missing like the Rand S&H. I wonder if I'm not with an old version of hemisphere, but I cant find in this GH repo whats the newest version. Sorry If the info is here I just cant find it.

**Comment by pablobcb** [comment]
I just saw theres a Hemisphere suite repo, with tons of stuff that are not included in the version I have, why there are two repos? If I want to update the firmware which version should I use

**Comment by Chysn** [comment]
Hi! I would recommend that you install Hemisphere Suite from the newest release here:

https://github.com/Chysn/O_C-HemisphereSuite/releases

Please take care to read all release notes.

To answer your question about sample and hold: it’s in Calculator now as one of the operations. To see the documentation, follow the link above and click on Wiki.

Regards,
Jason

**Comment by pablobcb** [comment]
Hey,  thank you for the fast support, I am also a programmer (as you can see), and really would like to try to write something for the o_C, do you have an e-mail where I can make some questions without polluting the GH issues?

**Comment by Chysn** [comment]
I just updated my profile with my email address, so you can feel free to contact me there.

If you're interested in O_C development, I'd suggest reading my blog from the beginning: https://butmostlycrime.blogspot.com/
